Repository LingmoOS/lingmo-settings, pull requests merged in 2025-03, with the labels that each got.

#53 build: fix ICU compile flags
  CMakeLists.txt
  debian/changelog
Labels: 🚀 merge it!

#54 build(CMake): add uc from libicu
  CMakeLists.txt
Labels: bug, 🚀 merge it!

#56 ci: add workflow_dispatch
  .github/workflows/build.yml
Labels: 🚀 merge it!

#57 fix: Change elog to new lingmo logger module in liblingmo.
  .github/workflows/Auto CI Test Build.yml
  CMakeLists.txt
  debian/changelog
  src/application.cpp
  src/main.cpp
  src/qml/main.qml
Labels: enhancement, 🚀 merge it!
